# Generated by Django 3.2.7 on 2021-10-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='website_products', to='base.Product'),
        ),
    ]
