# Generated by Django 3.2.7 on 2021-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='header_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='header_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
