# Generated by Django 3.2.7 on 2021-10-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211016_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='website',
            name='header_title',
        ),
    ]
